from fundamentals.analysis.book_value_plus_dividends_increasing import BookValuePlusDividendsIncreasing
from fundamentals.analysis.cash_from_operating_activities_increasing import CashFromOperatingActivitiesIncreasing
from fundamentals.analysis.net_income_increasing import NetIncomeIncreasing
from fundamentals.analysis.revenue_sales_increasing import RevenueSalesIncreasing
from fundamentals.analysis.total_equity_increasing import TotalEquityIncreasing
from fundamentals.analysis.total_revenue_increasing import TotalRevenueIncreasing
from fundamentals.analysis.roe_higher_than_industry import RoeHigherThanIndustry
from fundamentals.analysis.npm_higher_than_industry import NpmHigherThanIndustry
